version: "3.9"

volumes:
  data-redis:
    driver: local

services:
  synchronizers:
    image: darchlabs/synchronizer-v2:1.2.0
    ports:
      - 5555:5555
    env_file:
      - .env.synchronizers

  jobs:
    image: darchlabs/jobs:1.1.3
    ports:
      - 3030:3030
    env_file:
      - .env.jobs

  nodes:
    image: darchlabs/nodes:1.0.0
    env_file:
      - .env.node
    restart: on-failure
    ports:
      - "8545-8595:8545-8595"
      - "6969:6969"
    volumes:
      - ../data:/home/nodes/data:rw

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - data-redis:/data-redis
